use_frameworks!

target 'VCUIKit_Example' do
  pod 'VCUIKit', :path => '../'

pod 'SwiftMessages', '3.1.5'

pod 'SWActivityIndicatorView', '2.0.0'

pod 'SnapKit', '3.2.0'

pod 'FCAlertView', '1.3.1'

pod 'DKImagePickerController', '3.5.0'

pod 'ActionSheetPicker-3.0', '2.2.0'

pod 'SVProgressHUD', '2.1.2'

  target 'VCUIKit_Tests' do
    inherit! :search_paths

    
  end
end
