use_frameworks!

target 'VCUIKit_Example' do
  pod 'VCUIKit', :path => '../'

pod 'SwiftMessages', '3.1.5'

pod 'SWActivityIndicatorView', '2.0.0'

pod 'SnapKit', '3.2.0'

pod 'PullToRefreshSwift', '3.0.3'

pod 'FCAlertView', '1.3.1'

pod 'DKImagePickerController', '3.5.0'

pod 'EPSignature', '1.0.3'

pod 'ActionSheetPicker-3.0', '2.2.0'

pod 'DCAnimationKit', '0.0.6'

  target 'VCUIKit_Tests' do
    inherit! :search_paths

    
  end
end
